# Check out https://docs.codemagic.io/yaml/building-a-react-native-app/ for more information
# Please review and update values in curly braces

workflows:
  react-native:
    name: React Native App
    environment:
      vars:
        XCODE_WORKSPACE: 'VicophaQR.xcworkspace'
        XCODE_SCHEME: 'VicophaQR'
      node: latest
    scripts:
      - yarn
      - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
      - |
        # build Android
        cd android
        ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
